#This file is used to configure csv drivers. For each equipment fill 4 lines as in the following examples. Name must be the same as the equipment name

Name: Temp_Mercury
Path: /media/Mercury_dati/
Basefile: Mercury_
Extension: .txt
Header_line: 0

Name: Temp_FP
Path: /media/avs-47/
Basefile: logFP___
Extension: .dat
Header_line: 0

Name: Temp_AVS
Path: /media/avs-47/
Basefile: LogAVS___
Extension: .dat
Header_line: 2