#This file is used to configure csv drivers. For each equipment fill 4 lines as in the following examples. Name must be the same as the equipment name

Name: Environment
Path: /home/cold/daq/online/userfiles/Mercury_dati/
Basefile: Mercury_
Extension: .txt

Name: Environment2
Path: /home/cold/daq/online/userfiles/avs47/
Basefile: logFP___
Extension: .dat

Name: Temp_Mercury
Path: /media/Mercury_dati/
Basefile: Mercury_
Extension: .txt

Name: Temp_AVS_FP
Path: /media/avs-47/
Basefile: logFP___
Extension: .dat

Name: Temp_AVS_FP
Path: /media/avs-47/
Basefile: LogAVS___
Extension: .dat